apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sanke-game-js
  description: A service that provides an API for managing users.
  tags:
    - javascript
  annotations:
    custom.reposecretes: "Masterful"
    custom.baseImageScans: "Certified"
    custom.componentLibraries: "Opportunity for Improvement"
  links:
    - url: https://my-service.example.com
      title: Live Service
      icon: link
spec:
  type: service
  lifecycle: development
  owner: team-a
